modLoader = "javafml"
loaderVersion = "[37, 49,)"
license = "Public Domian"
[[mods]]
modId = "mousekeyinventoryfix"
version = "${version}"
displayName = "Mouse Key Inventory Fix"
logoFile = "mousekeyinventoryfix_icon.png"
authors = "Elephant_1214"
description = '''
    Fixes the almost ten-year-old issue with mouse key binds not working in inventories.
    '''
[[dependencies.mousekeyinventoryfix]]
modId = "forge"
mandatory = true
versionRange = "[37, 49,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.mousekeyinventoryfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1, 1.20.4)"
ordering = "NONE"
side = "CLIENT"